name: Auto PR - CLI

on:
  # schedule:
  #   - cron: "00 00 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we get all history and branches

      # Set up Git and fetch all branches
      - name: Configure Git and Fetch
        run: |
          git config user.email "183369419+github-actions[bot]@users.noreply.github.com"
          git config user.name "A"
          git fetch --all  # Fetch all branches to avoid "refspec doesn't match any" error
          git branch -a  # Debug: List all branches

      # Create a new branch for the changes
      - name: Create new branch for update
        run: |
          BRANCH_NAME="update-readme-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV  # Store for later steps

      # Append timestamp to README.md
      - name: Append timestamp to README.md
        run: |
          echo "Appending update timestamp to README.md"
          TIMESTAMP="update-readme-$(date +'%Y%m%d%H%M%S')"
          echo $TIMESTAMP >> README.md  # Append to README.md

      # Commit and push changes if README.md was updated
      - name: Commit and push changes
        env:
            GH_TOKEN: ${{ secrets.PAT_TOKEN }}      
        run: |
          git add README.md
          git commit -m "Automated update to README.md"
          
          # Debugging: Verify remote
          git remote -v

          # Push the new branch and set upstream
          git push -u origin $BRANCH_NAME

      # Create pull request
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Automated update for README.md" \
            --body "This PR updates README.md with a new timestamp." \
            --base main \
            --head $BRANCH_NAME
