# 183369419+as2024ad@users.noreply.github.com
# A

# - the sitemap is generated in the ./Utilities folder
# - move the sitemap from ./Utilities to www folder, replacing the sitemap currently in there
# - update the delete branches setting

name: Auto PR-WORKING-COPY

on:
  schedule:
    - cron: "35 14 * * *"
  workflow_dispatch:

# complete the GitHub workflow:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # - generate a mock sitemap in the ./Utilities folder
      # - name: Generate mock sitemap
      #   run: |
      #     cat > Utilities/sitemap.xml <<EOL
      #     <?xml version="1.0" encoding="UTF-8"?>
      #     <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      #       <url><loc>https://example.com/</loc></url>
      #     </urlset>
      #     EOL

      - name: Generate mock sitemap
        run: |
          # Generate the basic sitemap
          cat > Utilities/sitemap.xml <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://example.com/</loc>
              <lastmod>$(date +'%Y%m%d%H%M%S')</lastmod>
            </url>
          </urlset>
          EOL
        

      # move the sitemap from ./Utilities to ./app-directory/wwwroot, replacing the sitemap currently in there
      - name: Move sitemap to target directory
        run: |
          mv -f Utilities/sitemap.xml app-directory/wwwroot/sitemap.xml


        # make this script work to replace the branch name in peter-evans/create-pull-request@v7
      - name: Set dynamic branch name
        run: echo "BRANCH_NAME=sitemap-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        #run: echo "create-pull-request/sitemap-$(date +'%Y%m%d%H%M%S')"




      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Sitemap latest updates
          #committer: github-actions[bot] <183369419+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/sitemap-12345
          delete-branch: false
          title: "Sitemap Change"
          body: |
            Please review the latest changes to the sitemap.
          # labels: |
          #   report
          #   automated pr
          # assignees: as2024ad
          # reviewers: as2024ad
          # team-reviewers: |
          #   developers
          #   qa-team
          #milestone: 1
          draft: false
