# 183369419+as2024ad@users.noreply.github.com
# A

# - the sitemap is generated in the ./Utilities folder
# - move the sitemap from ./Utilities to www folder, replacing the sitemap currently in there
# - update the delete branches setting

name: Auto PR-WORKING-COPY

on:
  schedule:
    - cron: "50 14 * * *"
  workflow_dispatch:

# complete the GitHub workflow:
jobs:
  createPullRequest:
    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v4

      - name: Generate mock sitemap
        run: |
          # Generate the basic sitemap
          cat > Utilities/sitemap.xml <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://example.com/</loc>
              <lastmod>$(date +'%Y%m%d%H%M%S')</lastmod>
            </url>
          </urlset>
          EOL
        

      - name: Move sitemap to target directory
        run: |
          mv -f Utilities/sitemap.xml app-directory/wwwroot/sitemap.xml

      # - name: Set dynamic branch name
      #   run: echo "BRANCH_NAME=create-pull-request/sitemap-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # - name: Set dynamic PR title with today's date
      #   run: echo "PR_TITLE=Sitemap change $(date '+%A %-dth %B %Y')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          BRANCH_NAME: create-pull-request/sitemap-${{ github.run_id }}
          PR_TITLE: Sitemap change $(date '+%A %d-%m-%Y')
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Sitemap latest updates
          #committer: github-actions[bot] <183369419+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: false
          title: ${{ env.PR_TITLE }}
          body: |
            Please review the latest changes to the sitemap.
          # labels: |
          #   report
          #   automated pr
          # assignees: as2024ad
          # reviewers: as2024ad
          # team-reviewers: |
          #   developers
          #   qa-team
          #milestone: 1
          draft: false
