# 183369419+as2024ad@users.noreply.github.com
# A

name: Auto PR for README Update

on:
  schedule:
    - cron: "58 15 * * *" # Runs daily at 14:35 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #    fetch-depth: 0  # Ensure the full history is fetched

      # Check for changes in the README.md file
      #   - name: Check for file changes
      #     run: |
      #       if git diff --quiet HEAD~1 -- README.txt; then
      #         echo "has_changes=false" >> $GITHUB_ENV
      #       else
      #         echo "has_changes=true" >> $GITHUB_ENV
      #       fi

      - name: Create new branch for update
        run: |
          BRANCH_NAME="update-readme-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME

      - name: Append timestamp to README.txt
        run: |
          echo "Appending update timestamp to README.txt"
          TIMESTAMP="update-readme-$(date +'%Y%m%d%H%M%S')"
          echo $TIMESTAMP >> README.txt  # Append to README.txt

      - name: Commit and push changes
        run: |
          git add .
          git config user.email "183369419+as2024ad@users.noreply.github.com"
          git config user.name "A"        
          git add README.txt
          git commit -m "Automated update to README.txt"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Automated update for README.txt" \
            --body "This PR updates README.txt with a new timestamp." \
            --base main \
            --head $BRANCH_NAME
