# name: Trivy
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   build:
#     name: Trivy File Scan
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run Trivy vulnerability scanner in repo mode
#         uses: aquasecurity/trivy-action@0.29.0
#         with:
#           scan-type: "fs"
#           ignore-unfixed: false
#           format: "sarif"
#           output: "trivy-results.sarif"
#           severity: "CRITICAL,HIGH,MEDIUM,LOW"
#           exit-code: 1

#       - name: Upload Trivy scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: "trivy-results.sarif"

#       - name: Print Trivy scan results
#         run: cat trivy-results.sarif

name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "json"
          output: "trivy-results.json"
          no-progress: true
          exit-code: 1
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          ignore-policy: .trivyignore
          quiet: true
          debug: true

      - name: Convert Trivy JSON to SARIF
        run: |
          npm install -g @trivycloud/trivy-to-sarif
          trivy-to-sarif trivy-results.json > trivy-results.sarif

      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif-file: trivy-results.sarif
